const TASK_STATUS = {
  QUEUED: "QUEUED",
  RUNNING: "RUNNING",
  COMPLETED: "COMPLETED",
  FAILED: "FAILED",
  CANCELLED: "CANCELLED",
  DEAD_LETTER: "DEAD_LETTER",
};

const TASK_TYPE = {
  IMAGE_PROCESSING: "IMAGE_PROCESSING",
  REPORT_GENERATION: "REPORT_GENERATION",
  DATA_IMPORT: "DATA_IMPORT",
  EMAIL_NOTIFICATION: "EMAIL_NOTIFICATION",
  FILE_CONVERSION: "FILE_CONVERSION",
};

module.exports = { TASK_STATUS, TASK_TYPE };
